services:
  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: diabetes
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    container_name: app
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: npm install && npm run dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://user:password@db:5432/diabetes
    ports:
      - '3000:3000'
    depends_on:
      - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    depends_on:
      - db

volumes:
  db_data:
