version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: diabetes
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: npm install && npm run dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://user:password@db:5432/diabetes
    ports:
      - '3000:3000'
    depends_on:
      - db

  phppgadmin:
    image: dockage/phppgadmin
    environment:
      PHP_PG_ADMIN_SERVER_HOST: db
      PHP_PG_ADMIN_SERVER_PORT: 5432
      PHP_PG_ADMIN_DEFAULT_USER: user
      PHP_PG_ADMIN_DEFAULT_PASSWORD: password
    ports:
      - '8080:80'
    depends_on:
      - db

volumes:
  db_data:
