openapi: 3.0.3
info:
    title: Diabetes Exercise API
    version: 1.0.0
    description: API for managing and retrieving exercises from the diabetes exercise library.
servers:
    - url: http://localhost:3000
paths:
    /exercises:
        get:
            summary: Get paginated list of exercises
            description: Returns a paginated list of exercises from the exercise library.
            parameters:
                - in: query
                  name: limit
                  schema:
                      type: integer
                      default: 20
                      minimum: 1
                      maximum: 100
                  description: Number of exercises per page
                - in: query
                  name: page
                  schema:
                      type: integer
                      default: 1
                      minimum: 1
                  description: Page number
            responses:
                '200':
                    description: A paginated list of exercises
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    data:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/Exercise'
                                    pagination:
                                        type: object
                                        properties:
                                            total:
                                                type: integer
                                                description: Total number of exercises available
                                            page:
                                                type: integer
                                                description: Current page number
                                            limit:
                                                type: integer
                                                description: Number of exercises per page
                                            totalPages:
                                                type: integer
                                                description: Total number of pages available
                                            hasMore:
                                                type: boolean
                                                description: Indicates if there are more pages after the current one
                                            count:
                                                type: integer
                                                description: Number of results in the current page
                '500':
                    description: Failed to fetch exercises
components:
    schemas:
        Exercise:
            type: object
            properties:
                id:
                    type: string
                name:
                    type: string
                force:
                    type: string
                    nullable: true
                level:
                    type: string
                    nullable: true
                mechanic:
                    type: string
                    nullable: true
                equipment:
                    type: string
                    nullable: true
                primary_muscles:
                    type: array
                    items:
                        type: string
                secondary_muscles:
                    type: array
                    items:
                        type: string
                instructions:
                    type: array
                    items:
                        type: string
                category:
                    type: string
                    nullable: true
                images:
                    type: array
                    items:
                        type: string
                image_urls:
                    type: array
                    items:
                        type: string
                created_at:
                    type: string
                    format: date-time
